name: Setup

runs:
  using: "composite"
  steps:
    - name: setup git-restore-mtime
      run: |
        sudo apt-get install -y git-restore-mtime
      shell: bash
    - name: setup blogsync
      uses: x-motemen/blogsync@887d46259abad712a468f053a0791befb9b38029 # v0.21.1
      with:
        version: v0.20.1
    - name: restore mtime
      run: |
        git restore-mtime
      shell: bash
