name: Setup

runs:
  using: "composite"
  steps:
    - name: setup git-restore-mtime
      run: |
        sudo apt-get install -y git-restore-mtime
      shell: bash
    - name: setup blogsync
      uses: x-motemen/blogsync@9760a4c471a07ca7d471dd9f09ecbb258f6da6b0 # v0.20.1
      with:
        version: v0.20.1
    - name: restore mtime
      run: |
        git restore-mtime
      shell: bash
