name: create draft pull request

inputs:
  title:
    required: true
  BLOG_DOMAIN:
    required: true
  ENTRY_PATH:
    required: true

runs:
  using: "composite"
  steps:
    - name: set entry variables
      id: set-entry-variables
      run: |
        echo "EDIT_URL=$(yq --front-matter=extract '.EditURL' ${{ inputs.ENTRY_PATH }})" >> $GITHUB_OUTPUT
        echo "ENTRY_ID=$(yq --front-matter=extract '.EditURL' ${{ inputs.ENTRY_PATH }} | grep -oP '[^/]+\d$')" >> $GITHUB_OUTPUT
        echo "PREVIEW_URL=$(yq --front-matter=extract '.PreviewURL' ${{ inputs.ENTRY_PATH }})" >> $GITHUB_OUTPUT
      shell: bash
    - name: set owner
      id: set-owner
      run: |
        owner=$(yq ".[\"${{ inputs.BLOG_DOMAIN }}\"].owner" blogsync.yaml)
        if [[ "$owner" == 'null' ]]; then
          owner=$(yq ".[\"${{ inputs.BLOG_DOMAIN }}\"].username" blogsync.yaml)
        fi
        echo "OWNER_NAME=$owner" >> $GITHUB_OUTPUT
      shell: bash
    - name: delete other files
      run: |
        delete_files=($(grep -xL "EditURL: ${{ steps.set-entry-variables.outputs.EDIT_URL }}" $(git ls-files -mo --exclude-standard)))
        for file in ${delete_files[@]}; do
          rm "$file"
        done
      shell: bash
    - name: move draft and update metadata
      uses: hatena/hatenablog-workflows/.github/actions/move-draft-and-update-metadata@current
    - name: create pull request
      uses: peter-evans/create-pull-request@v5
      env:
        OWNER_NAME: ${{ steps.set-owner.outputs.OWNER_NAME }}
        ENTRY_ID: ${{ steps.set-entry-variables.outputs.ENTRY_ID }}
        PREVIEW_URL: ${{ steps.set-entry-variables.outputs.PREVIEW_URL }}
      with:
        title: ${{ github.event.inputs.title }}
        branch: draft-entry-${{ env.ENTRY_ID }}
        body: |
          ## ${{ github.event.inputs.title }}

          - 編集ページのURL: https://blog.hatena.ne.jp/${{ env.OWNER_NAME }}/${{ inputs.BLOG_DOMAIN }}/edit?entry=${{ env.ENTRY_ID }}
          - プレビューへのURL: ${{ env.PREVIEW_URL == 'null' && 'なし' || env.PREVIEW_URL }}
        delete-branch: true
