name: "[Reusable workflows] initialize"

on:
  workflow_call:
    inputs:
      BLOG_DOMAIN:
        required: true
        type: string
    secrets:
      OWNER_API_KEY:
        required: true

jobs:
  initialize:
    env:
      BLOGSYNC_PASSWORD: ${{ secrets.OWNER_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup blogsync
        uses: x-motemen/blogsync@v0
        with:
          version: latest
      - name: pull
        run: |
          blogsync pull ${{ inputs.BLOG_DOMAIN }}
      - name: move draft and update metadata
        run: |
          draft_files=($(grep -xl 'Draft: true' $(git ls-files -mo --exclude-standard)))
          for file in ${draft_files[@]}; do
            entry_id=$(yq --front-matter=extract '.EditURL' "$file" | grep -oP '[^/]+\d')
            yq --front-matter=process -i 'del(.Date,.URL)' "$file" 
            mv "$file" "draft_entries/$entry_id.${file##*.}"
          done
      - name: create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          title: initialize
          branch: initialize
          commit-message: |
            initialize
          body: |
            initialize
          delete-branch: true
