name: "[Reusable workflows] initialize"

on:
  workflow_call:
    inputs:
      BLOG_DOMAIN:
        required: true
        type: string
    secrets:
      OWNER_API_KEY:
        required: true

jobs:
  initialize:
    env:
      BLOGSYNC_PASSWORD: ${{ secrets.OWNER_API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup blogsync
        uses: x-motemen/blogsync@v0
        with:
          version: latest
      - name: pull
        run: |
          blogsync pull ${{ inputs.BLOG_DOMAIN }}
      - name: move draft and update metadata
        uses: hatena/hatenablog-workflows/.github/actions/move-draft-and-update-metadata@main
      - name: create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          title: initialize
          branch: initialize
          commit-message: |
            initialize
          body: |
            initialize
          delete-branch: true
