name: "[Reusable workflows] pull from hatenablog"

on:
  workflow_call:
    inputs:
      BLOG_DOMAIN:
        required: true
        type: string
      runner:
        required: false
        default: ubuntu-latest
        type: string
    secrets:
      OWNER_API_KEY:
        required: true

jobs:
  pull:
    runs-on: ${{ inputs.runner }}
    env:
      BLOGSYNC_PASSWORD: ${{ secrets.OWNER_API_KEY }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: resolve working directory
        id: working-directory
        uses: hatena/hatenablog-workflows/.github/actions/resolve-working-directory@cb4a9e94aa1400beceb5d9a99c772322b7fd6fc8
      - name: setup
        uses: hatena/hatenablog-workflows/.github/actions/setup@cb4a9e94aa1400beceb5d9a99c772322b7fd6fc8 
      - name: set blog domain
        id: set-domain
        run: |
          domain=${{ inputs.BLOG_DOMAIN }}
          echo "BLOG_DOMAIN=$(echo $domain | tr -d '\n\r ')" >> "$GITHUB_OUTPUT"
      - name: pull
        run: |
          blogsync pull ${{ steps.set-domain.outputs.BLOG_DOMAIN }}
        working-directory: ${{ steps.working-directory.outputs.working_directory }}
      - name: delete draft files
        run: |
          git ls-files -zmo --exclude-standard -- '*.md' | while IFS= read -r -d '' f; do
            if [[ -f "$f" ]] && [[ -n "$(yq --front-matter=extract 'select(.Draft == true)' "$f" 2>/dev/null)" ]]; then
              rm "$f"
            fi
          done
        working-directory: ${{ steps.working-directory.outputs.working_directory }}
      - name: create pull request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          title: blogsync pull
          branch: blogsync-pull
          commit-message: |
            blogsync pull
          body: |
            blogsync pull
          labels: |
            skip-push
          delete-branch: true
