name: "[Reusable workflows] push draft to hatena blog"

on:
  workflow_call:
    inputs:
      runner:
        required: false
        default: ubuntu-latest
        type: string
    secrets:
      OWNER_API_KEY:
        required: true

jobs:
  upload-images:
    uses: hatena/hatenablog-workflows/.github/workflows/upload-images.yaml@ed4c22897bcc6c971686a0a2c0d9d49dddd02f47 
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
  push-draft:
    if: always()
    needs: upload-images
    runs-on: ${{ inputs.runner }}
    env:
      BLOGSYNC_PASSWORD: ${{ secrets.OWNER_API_KEY }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ needs.upload-images.result == 'success' && needs.upload-images.outputs.revision || '' }}
          fetch-depth: 0
      - name: setup
        uses: hatena/hatenablog-workflows/.github/actions/setup@ed4c22897bcc6c971686a0a2c0d9d49dddd02f47 
      - name: Get changed draft files
        id: changed-draft-files
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: draft_entries/**/*.md
      - name: push only draft entry
        run: |
          for file in ${{ steps.changed-draft-files.outputs.all_changed_files }}; do
            draft=$(yq --front-matter=extract 'select(.Draft == true)' "$file")
            editurl=$(yq --front-matter=extract 'select(.EditURL == "https://blog.hatena.ne.jp/*")' "$file")
            if [[ -n "$draft" ]] && [[ -n "$editurl" ]]; then
              blogsync push "$file"
            fi
          done
