name: "[Reusable workflows] push published entries"

on:
  workflow_call:
    secrets:
      OWNER_API_KEY:
        required: true

jobs:
  upload-images:
    if: github.event.pull_request.merged == false
    uses: hatena/hatenablog-workflows/.github/workflows/upload-images.yaml@9d52996ed404a7b8aea5f3b5801853ad4ee44fdf # v1
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
