name: "[Reusable workflows] push published entries"

on:
  workflow_call:
    inputs:
      runner:
        required: false
        default: ubuntu-latest
        type: string
    secrets:
      OWNER_API_KEY:
        required: true

jobs:
  upload-images:
    if: github.event.pull_request.merged == false
    uses: hatena/hatenablog-workflows/.github/workflows/upload-images.yaml@34b59225b977353e671e6f643af6ceae40cba1f2
    with:
      runner: ${{ inputs.runner }}
    secrets:
      OWNER_API_KEY: ${{ secrets.OWNER_API_KEY }}
