name: "[Reusable workflows] push to hatena blog"

on:
  workflow_call:
    inputs:
      local_root:
        default: "entries"
        type: string
      runner:
        required: false
        default: ubuntu-latest
        type: string
    secrets:
      OWNER_API_KEY:
        required: true

jobs:
  push:
    if: |
      github.event.pull_request.merged == true
      && !contains(github.event.pull_request.labels.*.name, 'skip-push')
    runs-on: ${{ inputs.runner }}
    env:
      BLOGSYNC_PASSWORD: ${{ secrets.OWNER_API_KEY }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: setup
        uses: hatena/hatenablog-workflows/.github/actions/setup@6c7e0917c0ba2b68ccedc5710fd810805c91fa5f 
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          files: ${{ inputs.local_root }}/**/*.md
          since_last_remote_commit: true
      - name: blogsync push
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            draft=$(yq --front-matter=extract 'select(.Draft == true)' "$file")
            if [[ -z "$draft" ]]; then
              blogsync push "$file"
            fi
          done
