name: pull draft by title

inputs:
  title:
    description: draft entry title
    required: true
  BLOG_DOMAIN:
    required: true

runs:
  using: "composite"
  steps:
    - name: pull
      run: |
        blogsync pull ${{ inputs.BLOG_DOMAIN }}
      shell: bash
    - name: find entry
      id: find-entry
      run: |
        entry=$(grep -xl "Title: ${{ inputs.title }}" $(git ls-files -o --exclude-standard))
        if [[ -z "$entry" ]]; then
          echo "Error: No draft entry titled ${{ inputs.title }} was found"
          exit 1
        fi
        echo "ENTRY_ID=$(yq --front-matter=extract '.EditURL' "$entry" | grep -oP '[^/]+\d$')" >> $GITHUB_OUTPUT
        echo "PREVIEW_URL="$(yq --front-matter=extract '.PreviewURL'  "$entry")"" >> $GITHUB_OUTPUT
      shell: bash
    - name: set owner
      id: set-owner
      run: |
        owner=$(yq ".[\"${{ inputs.BLOG_DOMAIN }}\"].owner" blogsync.yaml)
        if [[ "$owner" == 'null' ]]; then
          owner=$(yq ".[\"${{ inputs.BLOG_DOMAIN }}\"].username" blogsync.yaml)
        fi
        echo "OWNER_NAME="$owner"" >> $GITHUB_OUTPUT
      shell: bash
    - name: delete other files
      run: |
        delete_files=($(grep -xL "Title: ${{ inputs.title }}" $(git ls-files -mo --exclude-standard)))
        for file in ${delete_files[@]}; do
          rm "$file"
        done
      shell: bash
    - name: move draft and update metadata
      uses: hatena/hatenablog-workflows/.github/actions/move-draft-and-update-metadata@v1
    - name: create pull request
      uses: peter-evans/create-pull-request@v5
      env:
        OWNER_NAME: ${{ steps.set-owner.outputs.OWNER_NAME }}
        ENTRY_ID: ${{ steps.find-entry.outputs.ENTRY_ID }}
        PREVIEW_URL: ${{ steps.find-entry.outputs.PREVIEW_URL }}
      with:
        title: ${{ github.event.inputs.title }}
        branch: draft-entry-${{ env.ENTRY_ID }}
        body: |
          ## ${{ github.event.inputs.title }}
          編集ページのURL
          https://blog.hatena.ne.jp/${{ env.OWNER_NAME }}/${{ inputs.BLOG_DOMAIN }}/edit?entry=${{ env.ENTRY_ID }}

          プレビュー用のURL
          ${{ env.PREVIEW_URL }}
        delete-branch: true
